sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t assafjh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true assafjh/docker-react npm run test